import json
import re

file_path = 'fase_4/script_hanif.ipynb'
with open(file_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# 1. Update Imports
nb['cells'][1]['source'] = [
    "import sys\n",
    "import os\n",
    "import mysql.connector\n",
    "import pandas as pd\n",
    "import re\n",
    "from datetime import datetime\n",
    "import pickle\n",
    "import json\n",
    "sys.path.append(os.path.abspath('..'))\n",
    "from config import get_db_config\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
]

# 2. Update Transformation Cell (index 4)
transformation_source = [
    "transformed_dfs = {}\n",
    "\n",
    "# --- HELPER FUNCTIONS ---\n",
    "def extract_int(s):\n",
    "    if pd.isna(s) or not str(s).strip(): return None\n",
    "    nums = re.findall(r'\\d+', str(s))\n",
    "    return int(nums[0]) if nums else None\n",
    "\n",
    "def extract_chars(s):\n",
    "    if pd.isna(s) or not str(s).strip(): return None\n",
    "    return re.sub(r'\\d+', '', str(s)).strip()\n",
    "\n",
    "def convert_ya_tidak(s):\n",
    "    if pd.isna(s): return 0\n",
    "    val = str(s).strip().lower()\n",
    "    return 1 if val == 'ya' else 0\n",
    "\n",
    "# --- TRANSFORMATION ---\n",
    "\n",
    "# 1. siswa -> siswa\n",
    "if 'siswa' in raw_data:\n",
    "    df = pd.DataFrame(raw_data['siswa'])\n",
    "    df['id_mitra'] = df['idmitra'].apply(extract_int)\n",
    "    \n",
    "    # Normalisasi Agama\n",
    "    agama_map = {\n",
    "        'kristen': 'Kristen Protestan', 'protestan': 'Kristen Protestan', \n",
    "        'katholik': 'Katolik', 'budha': 'Buddha', 'khonghucu': 'Konghucu'\n",
    "    }\n",
    "    def normalize_agama(a):\n",
    "        if pd.isna(a): return 'Islam'\n",
    "        a_clean = str(a).strip()\n",
    "        for k, v in agama_map.items():\n",
    "            if k in a_clean.lower(): return v\n",
    "        return a_clean\n",
    "    df['agama'] = df['agama'].apply(normalize_agama)\n",
    "\n",
    "    mapping = {\n",
    "        'idsiswa': 'id_siswa', 'tgl_daftar': 'tanggal_registrasi', 'domisili': 'domisili',\n",
    "        'nama_lengkap': 'nama_lengkap', 'panggilan': 'nama_panggilan', 'jkel': 'jenis_kelamin',\n",
    "        'nama_sekolah': 'asal_sekolah', 'level_sekolah': 'tingkat_sekolah', 'nama_ortu': 'nama_orang_tua',\n",
    "        'pekerjaan_ortu': 'pekerjaan_orang_tua', 'tmp_lahir': 'tempat_lahir', 'tgl_lahir': 'tanggal_lahir',\n",
    "        'no_induk': 'nomor_induk', 'email': 'email', 'idcalon': 'id_calon',\n",
    "        'provinsi': 'id_provinsi', 'kabupaten': 'id_kabupaten', 'kecamatan': 'id_kecamatan',\n",
    "        'kelurahan': 'id_kelurahan', 'id_mitra': 'id_mitra', 'nisn': 'nisn', 'nik': 'nik',\n",
    "        'kewarganegaraan': 'kewarganegaraan', 'agama': 'agama', 'rt': 'rt', 'rw': 'rw',\n",
    "        'kodepos': 'kode_pos', 'statussiswa': 'status_aktif', 'rekomen': 'rekomendasi',\n",
    "        'info': 'sumber_info', 'pembayaran': 'metode_pembayaran', 'nama_ayah': 'nama_ayah',\n",
    "        'pekerjaan_ayah': 'pekerjaan_ayah', 'jenjang_ayah': 'pendidikan_ayah', \n",
    "        'penghasilan_ayah': 'penghasilan_ayah', 'nama_ibu': 'nama_ibu', 'penghasilan_ibu': 'penghasilan_ibu',\n",
    "        'jenjang_ibu': 'pendidikan_ibu', 'nama_wali': 'nama_wali', 'pekerjaan_wali': 'pekerjaan_wali',\n",
    "        'jenjang_wali': 'pendidikan_wali', 'penghasilan_wali': 'penghasilan_wali',\n",
    "        'wapeserta': 'wa_siswa', 'wawalmur': 'wa_ortu', 'waadmin': 'wa_administrasi',\n",
    "        'sts_pengisian': 'status_pengisian', 'bukti': 'path_bukti_bayar', 'lulus': 'status_lulus_siswa',\n",
    "        'created_bukti': 'tanggal_upload_bukti'\n",
    "    }\n",
    "    df_final = df.rename(columns=mapping)\n",
    "    df_final['pekerjaan_ibu'] = None\n",
    "    df_final['deleted_at'] = None\n",
    "    target_cols = [c for c in list(mapping.values()) if c in df_final.columns] + ['pekerjaan_ibu', 'deleted_at']\n",
    "    transformed_dfs['siswa'] = df_final[target_cols]\n",
    "\n",
    "# 2. kursus_siswa\n",
    "transformed_dfs['kursus_siswa'] = pd.DataFrame(columns=['id_kursus_siswa', 'id_siswa', 'id_kursus', 'tanggal_mulai', 'metode_belajar', 'status_aktif', 'catatan'])\n",
    "\n",
    "# 3. siswa_keluar -> siswa_keluar\n",
    "if 'siswa_keluar' in raw_data:\n",
    "    df = pd.DataFrame(raw_data['siswa_keluar'])\n",
    "    mapping = {\n",
    "        'idsiswa_keluar': 'id_keluar', 'idsiswa': 'id_siswa',\n",
    "        'alasan': 'alasan_keluar', 'tanggal': 'tanggal_keluar'\n",
    "    }\n",
    "    df = df.rename(columns=mapping)\n",
    "    df['id_kursus'] = None\n",
    "    df['id_tag_keluar'] = None\n",
    "    transformed_dfs['siswa_keluar'] = df[list(mapping.values()) + ['id_kursus', 'id_tag_keluar']]\n",
    "\n",
    "# 4. mitra -> mitra\n",
    "if 'mitra' in raw_data:\n",
    "    df = pd.DataFrame(raw_data['mitra'])\n",
    "    df['id_mitra_new'] = df['idmitra'].apply(extract_int)\n",
    "    df['kode_mitra'] = df['idmitra'].apply(extract_chars)\n",
    "    \n",
    "    bool_cols = ['leapverse', 'kemitraan', 'elsa', 'classin', 'mitraleap']\n",
    "    for col in bool_cols:\n",
    "        df[col] = df[col].apply(convert_ya_tidak)\n",
    "        \n",
    "    mapping = {\n",
    "        'id_mitra_new': 'id_mitra', 'nama': 'nama_mitra', 'instansi': 'nama_instansi',\n",
    "        'namasekolah': 'nama_sekolah', 'lokasi': 'alamat_mitra', 'kepsek': 'nama_pimpinan',\n",
    "        'cp': 'kontak_mitra', 'status': 'status_mitra', 'visimisi': 'visi_misi',\n",
    "        'program': 'program_mitra', 'sdm': 'info_sdm', 'weakness': 'info_kelemahan',\n",
    "        'rekomen': 'rekomendasi_program', 'jenis': 'jenis_mitra', 'provinsi': 'provinsi_id',\n",
    "        'kotkab': 'kabupaten_id', 'jml': 'jumlah_siswa_mitra', 'bidang': 'bidang_usaha',\n",
    "        'leapverse': 'is_leapverse', 'kemitraan': 'status_kemitraan', 'tahun': 'tahun_bergabung',\n",
    "        'jeniskemitraan': 'tipe_kerjasama', 'elsa': 'is_elsa', 'classin': 'is_classin',\n",
    "        'mitraleap': 'is_mitra_leap', 'created_at': 'created_at', 'kode_mitra': 'kode_mitra'\n",
    "    }\n",
    "    transformed_dfs['mitra'] = df.rename(columns=mapping).reindex(columns=list(mapping.values()))\n",
    "\n",
    "# 5. mitra_note -> mitra_progres\n",
    "if 'mitra_note' in raw_data:\n",
    "    df = pd.DataFrame(raw_data['mitra_note'])\n",
    "    mapping = {\n",
    "        'idmnote': 'id_progres_mitra', 'idmitra': 'id_mitra',\n",
    "        'note': 'catatan_progres_mitra', 'idusers': 'id_user', 'status': 'status_progres_mitra',\n",
    "        'startdate': 'kemitraan_mulai', 'enddate': 'kemitraan_berakhir', 'created_at': 'created_at'\n",
    "    }\n",
    "    transformed_dfs['mitra_progres'] = df.rename(columns=mapping).reindex(columns=list(mapping.values()))\n",
    "\n",
    "# 6. mitra_users -> kemitraan_verifikator\n",
    "if 'mitra_users' in raw_data:\n",
    "    df = pd.DataFrame(raw_data['mitra_users'])\n",
    "    mapping = {\n",
    "        'idmusers': 'id_kemitraan', 'idmnote': 'id_progres_mitra', 'idusers': 'id_user'\n",
    "    }\n",
    "    transformed_dfs['kemitraan_verifikator'] = df.rename(columns=mapping).reindex(columns=list(mapping.values()))\n",
    "\n",
    "# 7. siswamitra -> siswa_mitra\n",
    "if 'siswamitra' in raw_data:\n",
    "    df = pd.DataFrame(raw_data['siswamitra'])\n",
    "    mapping = {\n",
    "        'idsiswa': 'id_sm', 'tgl_daftar': 'tanggal_daftar', 'domisili': 'alamat_domisili',\n",
    "        'nama_lengkap': 'nama_lengkap', 'panggilan': 'nama_panggilan', 'jkel': 'jenis_kelamin',\n",
    "        'nama_instansi': 'nama_instansi', 'level_sekolah': 'tingkat_sekolah',\n",
    "        'pekerjaan': 'pekerjaan_sm', 'tmp_lahir': 'tempat_lahir', 'tgl_lahir': 'tanggal_lahir',\n",
    "        'no_induk': 'nomor_induk_sm', 'email': 'email_sm', 'tlp': 'wa_sm',\n",
    "        'keluar': 'status_keluar_sm', 'idmitra': 'id_mitra'\n",
    "    }\n",
    "    df_final = df.rename(columns=mapping)\n",
    "    df_final['sertifikat_sm'] = None\n",
    "    transformed_dfs['siswa_mitra'] = df_final.reindex(columns=list(mapping.values()) + ['sertifikat_sm'])\n",
    "\n",
    "# 8. siswa_keluar_mitra -> siswa_mitra_keluar\n",
    "if 'siswa_keluar_mitra' in raw_data:\n",
    "    df = pd.DataFrame(raw_data['siswa_keluar_mitra'])\n",
    "    mapping = {\n",
    "        'idsiswa_keluar': 'id_sm_keluar', 'idsiswa': 'id_sm',\n",
    "        'alasan': 'alasan_keluar_sm', 'tanggal': 'tanggal_keluar_sm'\n",
    "    }\n",
    "    transformed_dfs['siswa_mitra_keluar'] = df.rename(columns=mapping).reindex(columns=list(mapping.values()))\n",
    "\n",
    "print(f\"✓ Transformasi {len(transformed_dfs)} tabel Fase 4 selesai.\")"
]
nb['cells'][7]['source'] = transformation_source

# 3. Add Verification Cells
verif_header_idx = -1
export_header_idx = -1

for i, cell in enumerate(nb['cells']):
    if cell['cell_type'] == 'markdown' and '## 3.1 Verifikasi Hasil Transformasi' in ''.join(cell['source']):
        verif_header_idx = i
    if cell['cell_type'] == 'markdown' and '## 4. Export ke Pickle' in ''.join(cell['source']):
        export_header_idx = i

if verif_header_idx != -1 and export_header_idx != -1:
    summary_counts_cell = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 3.1.1 Ringkasan Jumlah Baris\n",
            "print(\"\ud83d\udcca RINGKASAN MIGRASI (RECORDS COUNT)\")\n",
            "print(\"=\"*70)\n",
            "summary_list = []\n",
            "for old_t, new_t in hanif_tables_map:\n",
            "    old_c = len(raw_data.get(old_t, []))\n",
            "    new_c = len(transformed_dfs.get(new_t, []))\n",
            "    summary_list.append({\n",
            "        'Tabel Lama': old_t,\n",
            "        'Tabel Baru': new_t,\n",
            "        'Old Recs': old_c,\n",
            "        'New Recs': new_c,\n",
            "        'Diff': new_c - old_c,\n",
            "        'Status': \"\u2705 OK\" if old_c == new_c else \"\u26a0\ufe0f Cek\"\n",
            "    })\n",
            "display(pd.DataFrame(summary_list))\n",
            "\n",
            "total_old_all = sum(len(records) for records in raw_data.values())\n",
            "total_new_all = sum(len(df) for df in transformed_dfs.values())\n",
            "print(f\"\\n\ud83d\udce2 TOTAL REKAPITULASI: {total_old_all} (Old) \u2794 {total_new_all} (New)\")\n",
            "if total_old_all == total_new_all: print(\"\u2705 SEMUA DATA TERANGKUT\")\n",
            "else: print(f\"\u26a0\ufe0f ADA SELISIH: {total_new_all - total_old_all} baris\")"
        ]
    }

    specific_checks_cell = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 3.1.2 Output Pengecekan Kolom Spesifik (KETERANGAN mapping.md)\n",
            "print(\"\\n\ud83d\udd0d PENGECEKAN TRANSFORMASI SPESIFIK (KETERANGAN mapping.md)\")\n",
            "print(\"=\"*70)\n",
            "\n",
            "# 1. Pengecekan ID Mitra (Siswa)\n",
            "if 'siswa' in transformed_dfs:\n",
            "    print(\"\\n[SISWA] Pengecekan Ekstraksi ID Mitra (Int):\")\n",
            "    display(transformed_dfs['siswa'][['nama_lengkap', 'id_mitra']].dropna(subset=['id_mitra']).head(5))\n",
            "\n",
            "# 2. Pengecekan Agama (Siswa)\n",
            "if 'siswa' in transformed_dfs:\n",
            "    print(\"\\n[SISWA] Pengecekan Normalisasi Agama:\")\n",
            "    display(transformed_dfs['siswa']['agama'].value_counts())\n",
            "\n",
            "# 3. Pengecekan Mitra (Boolean & ID/Kode)\n",
            "if 'mitra' in transformed_dfs:\n",
            "    print(\"\\n[MITRA] Pengecekan Boolean (Ya/Tidak -> 1/0) & Kode Mitra:\")\n",
            "    display(transformed_dfs['mitra'][['nama_mitra', 'id_mitra', 'kode_mitra', 'is_leapverse', 'status_kemitraan']].head(5))\n",
            "\n",
            "# 4. Pengecekan Audit Trailing (Mitra & Progres)\n",
            "if 'mitra' in transformed_dfs:\n",
            "    print(\"\\n[MITRA] Pengecekan created_at (Direct Mapping):\")\n",
            "    display(transformed_dfs['mitra'][['nama_mitra', 'created_at']].head(5))"
        ]
    }

    detailed_checks_cell = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 3.1.3 Detail Perbandingan Kolom & Tipe Data (Side-by-Side)\n",
            "print(\"\\n\ud83d\udd0d PERBANDINGAN TIPE DATA SIDE-BY-SIDE\")\n",
            "for old_t, new_t in hanif_tables_map:\n",
            "    print(f\"\\n{'='*15} {old_t.upper()} \u2794 {new_t.upper()} {'='*15}\")\n",
            "    \n",
            "    df_old = pd.DataFrame(raw_data.get(old_t, []))\n",
            "    df_new = transformed_dfs.get(new_t, pd.DataFrame())\n",
            "    \n",
            "    if not df_new.empty or not df_old.empty:\n",
            "        comparison = []\n",
            "        table_mapping = {}\n",
            "        if old_t == 'siswa': table_mapping = {'idsiswa': 'id_siswa', 'tgl_daftar': 'tanggal_registrasi', 'domisili': 'domisili', 'nama_lengkap': 'nama_lengkap', 'panggilan': 'nama_panggilan', 'jkel': 'jenis_kelamin', 'nama_sekolah': 'asal_sekolah', 'level_sekolah': 'tingkat_sekolah', 'nama_ortu': 'nama_orang_tua', 'pekerjaan_ortu': 'pekerjaan_orang_tua', 'tmp_lahir': 'tempat_lahir', 'tgl_lahir': 'tanggal_lahir', 'no_induk': 'nomor_induk', 'email': 'email', 'idcalon': 'id_calon', 'provinsi': 'id_provinsi', 'kabupaten': 'id_kabupaten', 'kecamatan': 'id_kecamatan', 'kelurahan': 'id_kelurahan', 'idmitra': 'id_mitra', 'nisn': 'nisn', 'nik': 'nik', 'kewarganegaraan': 'kewarganegaraan', 'agama': 'agama', 'rt': 'rt', 'rw': 'rw', 'kodepos': 'kode_pos', 'statussiswa': 'status_aktif', 'rekomen': 'rekomendasi', 'info': 'sumber_info', 'pembayaran': 'metode_pembayaran', 'nama_ayah': 'nama_ayah', 'pekerjaan_ayah': 'pekerjaan_ayah', 'jenjang_ayah': 'pendidikan_ayah', 'penghasilan_ayah': 'penghasilan_ayah', 'nama_ibu': 'nama_ibu', 'penghasilan_ibu': 'penghasilan_ibu', 'jenjang_ibu': 'pendidikan_ibu', 'nama_wali': 'nama_wali', 'pekerjaan_wali': 'pekerjaan_wali', 'jenjang_wali': 'pendidikan_wali', 'penghasilan_wali': 'penghasilan_wali', 'wapeserta': 'wa_siswa', 'wawalmur': 'wa_ortu', 'waadmin': 'wa_administrasi', 'sts_pengisian': 'status_pengisian', 'bukti': 'path_bukti_bayar', 'lulus': 'status_lulus_siswa', 'created_at': 'created_at'}\n",
            "        elif old_t == 'siswa_keluar': table_mapping = {'idsiswa_keluar': 'id_keluar', 'idsiswa': 'id_siswa', 'alasan': 'alasan_keluar', 'tanggal': 'tanggal_keluar'}\n",
            "        elif old_t == 'mitra': table_mapping = {'idmitra': 'id_mitra', 'nama': 'nama_mitra', 'instansi': 'nama_instansi', 'namasekolah': 'nama_sekolah', 'lokasi': 'alamat_mitra', 'kepsek': 'nama_pimpinan', 'cp': 'kontak_mitra', 'status': 'status_mitra', 'visimisi': 'visi_misi', 'program': 'program_mitra', 'sdm': 'info_sdm', 'weakness': 'info_kelemahan', 'rekomen': 'rekomendasi_program', 'jenis': 'jenis_mitra', 'provinsi': 'provinsi_id', 'kotkab': 'kabupaten_id', 'jml': 'jumlah_siswa_mitra', 'bidang': 'bidang_usaha', 'leapverse': 'is_leapverse', 'kemitraan': 'status_kemitraan', 'tahun': 'tahun_bergabung', 'jeniskemitraan': 'tipe_kerjasama', 'elsa': 'is_elsa', 'classin': 'is_classin', 'mitraleap': 'is_mitra_leap', 'created_at': 'created_at'}\n",
            "        elif old_t == 'mitra_note': table_mapping = {'idmnote': 'id_progres_mitra', 'idmitra': 'id_mitra', 'note': 'catatan_progres_mitra', 'idusers': 'id_user', 'status': 'status_progres_mitra', 'startdate': 'kemitraan_mulai', 'enddate': 'kemitraan_berakhir', 'created_at': 'created_at'}\n",
            "        elif old_t == 'mitra_users': table_mapping = {'idmusers': 'id_kemitraan', 'idmnote': 'id_progres_mitra', 'idusers': 'id_user'}\n",
            "        elif old_t == 'siswamitra': table_mapping = {'idsiswa': 'id_sm', 'tgl_daftar': 'tanggal_daftar', 'domisili': 'alamat_domisili', 'nama_lengkap': 'nama_lengkap', 'panggilan': 'nama_panggilan', 'jkel': 'jenis_kelamin', 'nama_instansi': 'nama_instansi', 'level_sekolah': 'tingkat_sekolah', 'pekerjaan': 'pekerjaan_sm', 'tmp_lahir': 'tempat_lahir', 'tgl_lahir': 'tanggal_lahir', 'no_induk': 'nomor_induk_sm', 'email': 'email_sm', 'tlp': 'wa_sm', 'keluar': 'status_keluar_sm', 'idmitra': 'id_mitra'}\n",
            "        elif old_t == 'siswa_keluar_mitra': table_mapping = {'idsiswa_keluar': 'id_sm_keluar', 'idsiswa': 'id_sm', 'alasan': 'alasan_keluar_sm', 'tanggal': 'tanggal_keluar_sm'}\n",
            "\n",
            "        for old_col, new_col in table_mapping.items():\n",
            "            comparison.append({\n",
            "                'Old Column': old_col,\n",
            "                'Old Type': str(df_old[old_col].dtype) if not df_old.empty and old_col in df_old.columns else \"N/A\",\n",
            "                '\u2794': '\u2794',\n",
            "                'New Column': new_col,\n",
            "                'New Type': str(df_new[new_col].dtype) if not df_new.empty and new_col in df_new.columns else \"N/A\"\n",
            "            })\n",
            "        \n",
            "        # Cek kolom baru\n",
            "        if not df_new.empty:\n",
            "            for col in df_new.columns:\n",
            "                if col not in table_mapping.values():\n",
            "                    comparison.append({\n",
            "                        'Old Column': '(KOLOM BARU / CUSTOM)',\n",
            "                        'Old Type': '-',\n",
            "                        '\u2794': '\u2794',\n",
            "                        'New Column': col,\n",
            "                        'New Type': str(df_new[col].dtype)\n",
            "                    })\n",
            "        \n",
            "        display(pd.DataFrame(comparison))\n",
            "        if not df_new.empty:\n",
            "            print(f\"\\n--- SAMPLE DATA NEW (2 Baris) ---\")\n",
            "            display(df_new.head(2))\n",
            "    else:\n",
            "        print(f\"\u26a0\ufe0f Tabel {new_t} kosong.\")"
        ]
    }

    new_cells = nb['cells'][:verif_header_idx + 1]
    new_cells.append(summary_counts_cell)
    new_cells.append(specific_checks_cell)
    new_cells.append(detailed_checks_cell)
    new_cells.extend(nb['cells'][export_header_idx:])
    
    nb['cells'] = new_cells
    
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)
    print("Notebook Fase 4 updated successfully.")
else:
    print("Required headers not found in Fase 4 notebook.")
